### PR TITLE
Revisions in response to issue 23

### PR DESCRIPTION
**Pull request by chrisreading01**
Amendment to the calculatePointHighlighting subfunction to correct issues with a 7 point ascending or descending trend, flagged by @ThomUK

### CODE REVIEW

**Comment by ThomUK** [comment]
This fixes the problem I found, Chris, and all the tests are still passing.  

One minor glitch is that a repeated value in a rising or falling trend does not normally contribute to, or cancel, a trend.  
Here's a reference I found (happily, an old NHS document!) [see pp24](https://www.england.nhs.uk/improvement-hub/wp-content/uploads/sites/44/2017/11/A-guide-to-creating-and-interpreting-run-and-control-charts.pdf)

Examples in code:
```
#normal 7 point falling trend - your new code makes this work
set.seed(2) #make the rnorm function result repeatable
data <- rnorm(30) #some random data
data[1:7] <- c(1, 0.5, 0, -0.5, -1, -1.5, -2) #replace the first 7 points with an improving trend
date <- seq(as.Date("2021-03-22"), by = 1, length.out = 30) #some dates
df <- tibble(data, date) # make the dataframe
spc(df, "data", "date")

#7 point falling trend, with a pair of equal points in the middle (making 8 points total)
#ideally these should be special-cause (highlighted) points, because the equal point doesn't cancel the trend
set.seed(2) #make the rnorm function result repeatable
data <- rnorm(30) #some random data
data[1:8] <- c(1, 0.5, 0, -0.5, -0.5, -1, -1.5, -2) #replace the first 7 points with an improving trend
date <- seq(as.Date("2021-03-22"), by = 1, length.out = 30) #some dates
df <- tibble(data, date) # make the dataframe
spc(df, "data", "date")

#6 point falling trend, with a pair of equal points in the middle (making 7 points total)
#these should be common-cause (grey) points, because the equal point doesn't contribute to the trend.
set.seed(2) #make the rnorm function result repeatable
data <- rnorm(30) #some random data
data[1:7] <- c(1, 0.5, 0, -0.5, -0.5, -1, -1.5) #replace the first 7 points with an improving trend
date <- seq(as.Date("2021-03-22"), by = 1, length.out = 30) #some dates
df <- tibble(data, date) # make the dataframe
spc(df, "data", "date")
```

Also, would it be worth doing some re-naming so that this is easier to understand for our future selves?
- sixPointGrowth seems to refer to the points in a rising or falling trend (so could become sevenPointTrend)?
- sevenPointTrend seems to refer to consecutive points on one side of the mean (so could become sevenPointOneSideOfMean)?

If you did have time to do that it would be worth putting in a separate commit in the PR so that the different changes are obvious.  It's a nit-pick though, and I'm sure you've got plenty else to do!

**Review by ThomUK — COMMENTED** [review]
Reviewed above (I always miss this button)

**Comment by chrisreading01** [comment]
Thanks for reviewing so quickly Tom! Completely agree on the naming, I think the six point growth must be a misnomer from early days of developing the function when I wasn't certain how many ascending/descending points were required. I'll change these to your suggested alternatives. 

Regarding the two points of equal value, it makes sense to me for these not to break a run - however I've checked some dummy data in the NHSE/I excel tool this morning and it seems to break a run in their tool? 

[ascendingruntest.zip](https://github.com/nhs-r-community/NHSRplotthedots/files/6828751/ascendingruntest.zip)

**Comment by ThomUK** [comment]
Ah, good thinking to check the NHSEI tool. In that case it's probably worth merging as-is, and we can double-check with them at the next opportunity.

What do you think?

**Comment by chrisreading01** [comment]
I think that makes sense, although before merging I will amend the PR to change the field names as you suggested above. :)

**Pull request merged**
