### PR TITLE
Convert s3

### PR DESCRIPTION
**Pull request by tomjemmett**
this is an attempt to rewrite the package to use s3 generic's like plot, and to simplify the function's API's so arguments relating to the spc data itself sits in spc(), and plot arguments site with the plot() function.

### CODE REVIEW

**Comment by tomjemmett** [comment]
I think this is now pretty complete from my end - though, there are a couple of open PR's (#49, #50, #52) which I will need to reincorporate into this branch somehow. So while I've marked as ready for review, these other PR's should be merged first, or we should drop all of those PR's and recreate them after this PR is merged (I would say let's go for the former! I will probably rebase this PR)

**Comment by tomjemmett** [comment]
now with 100% test coverage

**Comment by chrisreading01** [comment]
Could we have a catch up please to understand these changes please @tomjemmett and the benefits of using the s3 approach? :)

**Comment by tomjemmett** [comment]
yep! I'm free most of next week bar Friday! Though I may be working slightly earlier in the morning's (want to watch the Olympics! 😆

**Review by chrismainey — APPROVED** [review]
Happy to approve.  It's a lot of changes to review with precision, but manual review and testing checks out.  Need now to address the functions visible in help in #66 and update helpfiles #65 .

**Pull request merged**
