### PR TITLE
Add ci actions

### PR DESCRIPTION
**Pull request by tomjemmett**
adds linting and code coverage reports

### CODE REVIEW

**Comment by tomjemmett** [comment]
make sure to merge #36 first, though once this is merged it will cause some conflicts. Looking quickly it appears the conflicts will be an "accept both" strategy 👍

**Comment by tomjemmett** [comment]
@chrismainey just resolved conflicts on this - waiting for tests to pass

**Review by chrismainey — COMMENTED** [review]
This all looks good, and tests have passed.  Can I just check the purpose, from understanding of the code rather than the background.  Actions is going to lint the code and highlight, as an unchecked annotation, anywhere it coding style does comply with linting rules?

**Comment by tomjemmett** [comment]
yep! we may need to tweak `.lintr` to apply the rules we care about (or, probably more likely, turn off rules we don't care for). currently it's only showing warnings for style issues, but it will pick up some bugs (e.g. missing parentheses or other issues a static code analysis tool can identify).

**Review by chrismainey — APPROVED** [review]
Happy with set up.

**Pull request merged**
