### PR TITLE
Fix lintr issues

### PR DESCRIPTION
**Pull request by tomjemmett**
resolves most of the lintr warnings. a few remain, largely around cyclometric complexity. May need to refactor these functions into smaller, simpler ones.

There is an outstanding warning around an unused variable (improvementDirection in R/spc.R#34) which I've created a TODO comment for.

Few optimisations have been implemented where I can see clear and obvious options. Tests pass, though it's probably worth checking this branch out and confirming it runs as expected.

### CODE REVIEW

**Comment by tomjemmett** [comment]
I can't see the development branch - so this is being merged straight into main. This branch was created off of development, so it will in effect become the merge of development->main

**Review by chrisreading01 — APPROVED** [review]
As I don't really understand lintr yet, and this contains a lot of incremental changes in one go, I think I'm prepared to go on trust and merge this since you know a lot more about development than I do Tom!  

Good spot on the improvementDirection reference not being required. I expect that was picked up with a bulk copy/paste of part of spc() into the first subfunction. It's not needed in that function now.

**Comment by tomjemmett** [comment]
before merging need to resolve r-cmd-check stuff

**Comment by chrismainey** [comment]
At least some of it will be resolved by rebuilding docs.  A couple of them are mismatches of .doc in the function and documentation.  Re-oxygenise the docs and that will sort.
Also, need to initialise variables:  rebaseGroup, fixPointsRN, upl, and lpl in `spcOptions`

**Comment by tomjemmett** [comment]
thanks @chrismainey - all those are now handled (hopefully!). Before merging it would be good for someone to check this branch out, run one or two examples and confirm it's still running as expected :-)

**Comment by chrisreading01** [comment]
Awww, I had just gone through and pasted .data$ everywhere but you beat me to it XD

**Comment by chrisreading01** [comment]
@tomjemmett  I have run my stock examples and they are producing the expected outputs.

**Pull request merged**
