### PR TITLE
Add option to label limits and mean using secondary y axis

### PR DESCRIPTION
**Pull request by francisbarton**
- [x] added unit tests
- [x] checked code coverage with `covr::report()` (should aim for 100%)
- [x] ran `devtools::document()`
- [x] ran `lintr::lint_package()`
- [ ] resolved all lint warnings and notes
- [x] ran `styler::style_pkg()` to make sure code matches the style guidelines
- [x] ran R-CMD CHECK and resolved all issues

This submission adds a `label_limits` Boolean flag to `ptd_create_ggplot()`. When turned on, this flag will add a secondary y axis to the plot, with labels that indicate the values of the UCL, LCL and mean. This is in response to issue #141 .

Suggestions for better names for the flag are welcomed.

The fork currently fails against 1 lintr criterion: cyclomatic complexity. By adding the new flag, another set of option combinations has now been added to the `ptd_create_ggplot()` function, which gives it a complexity value of 23, with the current linter limit set to 20.

Further changes included in this PR:
- the DESCRIPTION file now acknowledges the dependency on R >= 4.1 (this is due to the use of the base pipe, which was already in the code) - see discussion on the NHS-R Slack channel
- a package documentation file has been added using `usethis::use_package_doc()`
- infix namespacing functions (e.g. `dplyr::`) have now been added to most of the external function calls in the package, with just a few auxiliary/embedded functions (e.g. `across()`, `aes()`) being explicitly imported in the package documentation file. (Some overlap with the work in PR #180)
- the column name `mean` in `ptd_spc_standard()` has been replaced with the name `mean_col` (see issue #187). Referring lines of code as well as test snapshots have been updated to use the new name
- a couple of tests have been added for the new flag, and it's included in the ptd options validation function
- the `point_type` calculation logic in `ptd_calculate_point_type()` now specifies `special_cause_flag == 0` rather than `!special_cause_flag`, which I think had been raising an error/bug somewhere.
- `rlang::quo_name()` calls (a superseded function) have been replaced with `rlang::as_name()`

I have also done some code tidying:
- the params in `ptd_create_plotly` were nearly all documented with the same text as the params in `ptd_create_ggplot`, so I replaced these with an `@inheritParams` line for easier maintainability
- I have standardised on UK spellings e.g. centre and colour where possible (however, plotly code uses parameters that are US spelling only)
- I have standardised on lower case letters in hex codes
- I have reduced the line length criterion in the .lintr file to 92 characters, and edited most longer lines to meet this. (I prefer an 80 character line maximum but I thought 92 was at least better/tidier than 120 chars)

This will also close issue #187 if accepted.

### CODE REVIEW

**Comment by tomjemmett** [comment]
thanks! I think we need to merge #180 and #182 first. These are probably going to cause some merge conflicts by looking at the [comparison's of the branches](https://github.com/nhs-r-community/NHSRplotthedots/compare/improve_plotly_tooltips...francisbarton:NHSRplotthedots:secondary-axis) - hopefully these should be too problematic!

**Comment by francisbarton** [comment]
Thanks Tom. I think most of the issues will be 'stylistic' like linting, line length, and the use of `dplyr::` etc prefixes. Possibly an issue around adoption of the base pipe.

**Comment by tomjemmett** [comment]
I've attempted to resolve conflicts. If they fail will revert my commit and have another look!

**Comment by tomjemmett** [comment]
going to merge and apply some fixes in another PR. many thanks @francisbarton !

**Pull request merged**
