### PR TITLE
finish off plotly implementation

### LINKED ISSUE #126: Plotly implementation
Maybe with help from @AYu1804 ?

### PR DESCRIPTION
**Pull request by tomjemmett**
finishes off the plotly implementation by adding in unit tests and sorting out check issues

resolves #126

- [x] added unit tests and checked code coverage with `covr::report()` (should aim for 100%)
- [x] ran `devtools::document()`
- [x] ran `lintr::lint_package()` and resolved all lint warnings and notes
- [x] ran `styler::style_pkg()` to make sure code matches the style guidelines
- [x] ran R-CMD CHECK and resolved all issues

### CODE REVIEW

**Comment by marcosfabietti** [comment]
image
tested:

- with no target
- with target
- with less than 12 points
- changing icon position

everything looks good!

**Comment by tomjemmett** [comment]
I've just noticed there is a bug with icons and facetted plots - all of the icons get inserted in the top right of the plot, not the facet.

Thinking quickly about facets and icons, I can't really see a way that this could ever look sensible (the size of the icons would quickly start dominating the entire plot area). So, I suggest if the plots are facetted then we set icon position to "none" and give a warning if it wasn't already "none"

**Comment by marcosfabietti** [comment]
tested it and you are right! removing it is the way to go

**Review by ThomUK — APPROVED** [review]
This is a fantastic addition and I can't see any problems having run the code.  Amazing work!

**Pull request merged**
