### PR TITLE
changing from ggplot to plotly

### PR DESCRIPTION
**Pull request by marcosfabietti**
added a new function and changed ptd_create_ggplot.
This was done by mapping the ggplot to plotly command (90% of the heavy load), and for the icons I added them via plotly afterwards by mapping top/bottom/left/right to plotly syntax, while images are extracted from the online repo as plotly doesn't like so much the local files. If there were few data points, the warning is also added under the figure (it isn't mapped otherwise). 

comment: sizes work differently in plotly, so the default isn't 8 but 0.15.

### CODE REVIEW

**Comment by tomjemmett** [comment]
I think this is a breaking change as it is directly changing the output from ggplot to plotly, which I think in the main package would be an undesirable use.

That said, we should either make it so the code works for plotly directly, or create a separate method that creates a plotly object

**Review by tomjemmett — CHANGES_REQUESTED** [review]
can we leave `ptd_create_ggplot` unchanged, but create a new function `ptd_create_plotly` - this could call `ptd_create_ggplot` but set the `icons_position` to `"none"`. Instead you would pass that argument to your own icons function.

I want to have a bit of a think about how to load the icons in... I would far prefer to have the icons loaded from the package locally rather than connecting to the web. This is something that could easily fail (for instance, some orgs still to this day block github...). For now I think keep as is.

Can you run [`styler::style_pkg()`](https://styler.r-lib.org/reference/style_pkg.html) on the code also

Cheers!

**Comment by tomjemmett** [comment]
Will also need unit tests creating, though I'm happy to write those after merging this PR

**Comment by marcosfabietti** [comment]
- can we leave ptd_create_ggplot unchanged, but create a new function ptd_create_plotly - this could call ptd_create_ggplot but set the icons_position to "none". Instead you would pass that argument to your own icons function.

The new commit does this now, with ptd_create_ggplot being restored as it was.

- I want to have a bit of a think about how to load the icons in... I would far prefer to have the icons loaded from the package locally rather than connecting to the web. This is something that could easily fail (for instance, some orgs still to this day block github...). For now I think keep as is.

I have searched everywhere, but plotly only handles URLs as image sources. There doesn't seem to be a work around this.

Let me know what do you think of these changes and whether we change the readme file!.

**Review by tomjemmett — APPROVED** [review]
I’m merging into a separate branch for now, but that’s to try to resolve the broken actions and implement unit tests on the new code.

many thanks!

**Pull request merged**
