### PR TITLE
Changed text to put link on the words and removed 'here'

### PR DESCRIPTION
**Pull request by Lextuga007**
- [x] added unit tests and checked code coverage with `covr::report()` (should aim for 100%)
- [x] ran `devtools::document()`
- [x] ran `lintr::lint_package()` and resolved all lint warnings and notes
- [x] ran `styler::style_pkg()` to make sure code matches the style guidelines
- [x] ran R-CMD CHECK and resolved all issues

### CODE REVIEW

**Comment by tomjemmett** [comment]
Is this based off of #179? As that has some changes that will be in conflict to this (if it’s direct from main)

**Comment by Lextuga007** [comment]
Oh I checked #176 and saw that was merged but not #179 and this is a branch off the current main.

**Comment by Lextuga007** [comment]
I've made a change to a vignette, not README so there are no conflicts (I merged locally ok). Shall I leave this until you've done #179?

**Comment by tomjemmett** [comment]
ah, ok, I thought this change was needed in the readme. PR's are independent then, so I've marked that ready for review and will merge this now.

**Review by tomjemmett — CHANGES_REQUESTED** [review]
This text is out of date, I updated the readme in #179 to reflect NHS Improvement no longer existing. I also changed the text to be more concise. I would suggest that we make this document match the "overview" paragraph from the README file

**Comment by Lextuga007** [comment]
Good point! I'll make those changes.

**Review by tomjemmett — APPROVED** [review]

**Pull request merged**
