### PR TITLE
3 refactor validation to function

### PR DESCRIPTION
**Pull request by ThomUK**
This PR should close issue #3, by creating a validateParameters() function to do validation of user-supplied parameters:

* validateParameters() checks the user-supplied parameters, and throws an error if there is a problem (stopping code execution, and showing the user an error message).  Existing validation logic is removed from the main spc() function.  
* Errors are thrown if parameters are the wrong type, length, or an unexpected value.
* Unit tests confirm that errors are thrown when invalid parameters are supplied.

### CODE REVIEW

**Comment by tomjemmett** [comment]
@chrisreading01 can you review and approve? unit tests look good. I will add a PR to add R cmd check to this repo via github actions

**Comment by chrisreading01** [comment]
Extracting all the validation tests into a separate function looks good. Did we want to further subdivide the rest of the function, thinking back to previous conversations? What about splitting the spc data frame creation step and the plotting step (think Tom J and Chris M recommended taking this out altogether in fact and using an S3 method??)

**Comment by ThomUK** [comment]
Chris, those other bits are logged as separate issues. I've written some code for the plotting one - will try to get another PR done soon...

**Review by chrisreading01 — APPROVED** [review]
Looks good to me, happy to merge!

**Pull request merged**
