### PR TITLE
update icons

### PR DESCRIPTION
**Pull request by tomjemmett**
Switches to using icon files instead of the simple circles. Has the advantage of more closely matching the Excel tool, though there may be scaling issues with the icons being raster files and not vector graphics.

- [x] added unit tests and checked code coverage with `covr::report()` (should aim for 100%)
- [x] ran `devtools::document()`
- [x] ran `lintr::lint_package()` and resolved all lint warnings and notes
- [x] ran `styler::style_pkg()` to make sure code matches the style guidelines
- [x] ran R-CMD CHECK and resolved all issues

### CODE REVIEW

**Comment by tomjemmett** [comment]
This will work towards solving #162, by atleast using the standard icons. We may want to copy that table somewhere into the readme or the vignette?

**Comment by NHSmatthewcallus** [comment]
The icons were created with this PowerPoint file. Could you use this to create vector graphics?

[Summary Icons.pptx](https://github.com/nhs-r-community/NHSRplotthedots/files/9798456/Summary.Icons.pptx)

They are used in the MDC Power BI template and differ slightly from the Excel tool. The only noteworthy difference is with the purple icons – the arrows are directly up and down in the Excel tool, but the ones above are angled to the right to make them easier to differentiate in a summary table.

**Comment by tomjemmett** [comment]
used that powerpoint to generate SVG's, seems to be working. May need a bit of tweaking over time. Essentially, we need to load the SVG, render to a raster image, and add the raster to the plot (versus using pngs: we load a raster and add that to the plot).

Benefit of this approach is we could always render the icon to a sensible size before adding to the plot so we don't get scaling issues... at the moment though I render as a 100x100 pixel image and render that...

**Comment by ThomUK** [comment]
It looks great, Tom.  I can't find any problems and I'd say ready to merge...

**Review by ThomUK — APPROVED** [review]

**Pull request merged**
