### PR TITLE
Development rebase

### PR DESCRIPTION
**Pull request by tomjemmett**
This is an attempt to rebase development to match the main branch - there were a number of conflicts, see the commit's in this history made by me (all lablled resolve merge). My strategy was to always accept the HEAD (e.g. latest) commit, but this will need to be checked. CI/CD seems to be passing so far (3/4, just waiting for linux/dev version to run).

### CODE REVIEW

**Review by ThomUK — COMMENTED** [review]
Hi @tomjemmett . I'm a bit out of my depth on this and can't really review.  I would have attempted to merge the small number of commits that main was ahead on into development to unify them, then re-merge everything from development back to main.  That's probably not the right way to do it (and may not even have worked!), so your way is almost certainly better!

**Comment by tomjemmett** [comment]
workflow I used was:
```
git fetch main
git checkout -t origin/development # this checkouts out and tracks the remote branch
git rebase main
```
then, you need to resolve conflicts, followed by
```
git add . # or, the file you changed
git commit -m "resolve conflict...
git rebase --continue
```
you may need to repeat those 3 steps multiple times.

The idea of rebase is basically to roll back development to where it departed from main, adds the commits from main, then applies the commits from development back on top. this is why merge conflicts occur :-)

**Comment by tomjemmett** [comment]
should state - the review for this probably should more be to check this branch out locally, test it works as expected.

if you are on a forked branch, create an "upstream origin"

```
git remote add upstream git@github.com:nhs-r-community/NHSRplotthedots.git
```

you should then be able to check this branch out

```
git fetch upstream
git checkout -t upstream/development-rebase
```

you could check this out with another name
```
git checkout -b give_the_branch_another_name upstream/development-rebase
```

**Comment by chrismainey** [comment]
> git remote add upstream git@github.com:nhs-r-community/NHSRplotthedots.git

Just a wee SSH vs. https warning here, Tom's instructions are for SSH.  Replace the url with https://github.com/nhs-r-community/NHSRplotthedots.git if using https.

**Comment by chrismainey** [comment]
I just pulled that down and merged it into development.  No conflicts for me.  Seems to be working ok from what I can see.

**Pull request merged**
